[package]
name = "opalite_macro"
version = "0.1.0"
authors = ["Callym <hi@callym.com>"]

[lib]
proc-macro = true

[features]
internal = []

[dependencies]
syn = { version = "0.13", features = ["full"] }
quote = "0.5"
proc-macro2 = { version = "0.3", features = ["nightly"] }
