[package]
name = "opalite"
version = "0.1.0"
authors = ["Callym <hi@callym.com>"]

[dependencies]
anymap = "0.12"
failure = "0.1"
fibers = "0.1"
futures = "0.1"
uuid = { version = "0.5", features = ["v4"] }
