[package]
name = "opalite"
version = "0.1.0"
authors = ["Callym <hi@callym.com>"]

[dependencies]
anymap = "0.12"
failure = "0.1"
gfx_window_glutin = "0.12"
glutin = "0.13"
owning_ref = "0.3"
specs = "0.10"
specs-derive = "0.1"
winit = "0.10"
uuid = { version = "0.5", features = ["v4"] }

[dependencies.futures]
git = "https://github.com/rust-lang-nursery/futures-rs"
rev = "a7d08e6"

[dependencies.gfx-hal]
git = "https://github.com/gfx-rs/gfx"
rev = "506ba0a"

[dependencies.gfx-render]
git = "https://github.com/gfx-rs/gfx"
rev = "506ba0a"

[dependencies.gfx-backend-vulkan]
git = "https://github.com/gfx-rs/gfx"
rev = "506ba0a"
